language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

  licenses:
    - android-sdk-license-.+
    - '.+'

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

script: ./gradlew :noodle:build jacocoTestReport

after_success:
  — bash <(curl -s https://codecov.io/bash)

